<a href="https://colab.research.google.com/github/gong509/bda/blob/main/04w_array_stack_split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
a = np.arange(1, 13).reshape(3, 4)
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
c = np.arange(1, 6, 2)
c

array([1, 3, 5])

In [ ]:
import numpy as np

np.hstack((a,np.expand_dims(c, axis=1) ))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
np.column_stack((a, c))

array([[ 1,  2,  3,  4,  1],
       [ 5,  6,  7,  8,  3],
       [ 9, 10, 11, 12,  5]])

In [ ]:
import numpy as np

a = np.array([1,2,3])
b = np.array([4,5,6])

np.c_[a, b]

array([[1, 4],
       [2, 5],
       [3, 6]])

In [ ]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])
x


array([[1, 2, 3]])

In [ ]:
y

array([[4, 5, 6]])

In [ ]:
x.shape, y.shape

((1, 3), (1, 3))

In [ ]:
np.column_stack((x, y))

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x, y]

array([[1, 2, 3, 4, 5, 6]])

In [ ]:
np.c_[x, 10, 20, y]

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
np.column_stack((x, 10 ,20, y))

array([[ 1,  2,  3, 10, 20,  4,  5,  6]])

In [ ]:
import numpy as np

rg = np.random.default_rng(12345)
rg

Generator(PCG64) at 0x790ACB473D80

In [ ]:
rg.random()

0.22733602246716966

In [ ]:
rg.random(5)

array([0.31675834, 0.79736546, 0.67625467, 0.39110955, 0.33281393])

In [ ]:
rg.random((2, 3, 4))

array([[[0.59830875, 0.18673419, 0.67275604, 0.94180287],
        [0.24824571, 0.94888115, 0.66723745, 0.09589794],
        [0.44183967, 0.88647992, 0.6974535 , 0.32647286]],

       [[0.73392816, 0.22013496, 0.08159457, 0.1598956 ],
        [0.34010018, 0.46519315, 0.26642103, 0.8157764 ],
        [0.19329439, 0.12946908, 0.09166475, 0.59856801]]])

In [ ]:
import numpy as np

rg = np.random.default_rng(1)
rg.integers(0, 10, 3)

array([4, 5, 7])

In [ ]:
rg.integers(0, high=20, size=(3, 4))

array([[19,  0,  2, 16],
       [18,  4,  6, 17],
       [ 8,  5, 16,  5]])

In [ ]:
rg.integers(1, 7, (3, 4))

array([[3, 4, 4, 1],
       [1, 6, 5, 6],
       [4, 5, 2, 3]])

In [ ]:
import numpy as np

rg = np.random.default_rng(1)
rg.standard_normal(3)

array([0.34558419, 0.82161814, 0.33043708])

In [ ]:
rg.standard_normal((3, 4))

array([[-1.30315723,  0.90535587,  0.44637457, -0.53695324],
       [ 0.5811181 ,  0.3645724 ,  0.2941325 ,  0.02842224],
       [ 0.54671299, -0.73645409, -0.16290995, -0.48211931]])

In [ ]:
a = np.arange(1, 4)
b = np.arange(4, 7)
c = np.arange(7, 10)
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
p = np.arange(1, 7).reshape(2, 3)
q = np.arange(11, 17).reshape(2, 3)
r = np.arange(21, 27).reshape(2, 3)
p, q, r

(array([[1, 2, 3],
        [4, 5, 6]]),
 array([[11, 12, 13],
        [14, 15, 16]]),
 array([[21, 22, 23],
        [24, 25, 26]]))

In [ ]:
np.vstack((a, b, c))

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.vstack((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.hstack((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.hstack((p, q, r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
a, b, c

(array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9]))

In [ ]:
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack((p, q, r))

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a, b, c), axis=1)

AxisError: axis 1 is out of bounds for array of dimension 1

In [ ]:
np.concatenate((a, b, c), axis=None)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a, b, c), axis=-1)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate((p, q, r), axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.concatenate((p, q, r), axis=1)

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.concatenate((p, q, r), axis=None)

array([ 1,  2,  3,  4,  5,  6, 11, 12, 13, 14, 15, 16, 21, 22, 23, 24, 25,
       26])

In [ ]:
np.c_[a, b, c]

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack((a, b, c))

array([[1, 4, 7],
       [2, 5, 8],
       [3, 6, 9]])

In [ ]:
np.column_stack(a, b, c)

TypeError: column_stack() takes 1 positional argument but 3 were given

In [ ]:
np.c_[p, q, r]

array([[ 1,  2,  3, 11, 12, 13, 21, 22, 23],
       [ 4,  5,  6, 14, 15, 16, 24, 25, 26]])

In [ ]:
np.r_[a, b, c]

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.concatenate((a, b, c))

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
np.r_[p, q, r]

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])

In [ ]:
np.vstack((p, q, r))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [11, 12, 13],
       [14, 15, 16],
       [21, 22, 23],
       [24, 25, 26]])